version: '3.4'

volumes:
  mysqldata:
    driver: local

services:
  nginx:
    image: nginx
    volumes:
      - ./html:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80

  phpserver:
    build:
      context: docker/php
      target: php-base
    volumes:
      - ./:/var/www

  php:
    build:
      context: docker/php
      target: php-cli
    volumes:
      - ./:/var/www

  mysqlserver:
    image: mysql/mysql-server
    environment:
      MYSQL_DATABASE: dockerfordevs
      MYSQL_USER: dockerfordevs
      MYSQL_PASSWORD: 'd1ffp@ssword'
      MYSQL_ROOT_PASSWORD: 's3curep@assword'
    volumes:
      - mysqldata:/var/lib/mysql
