version: '2'

services:
  webserver:
    image: php:apache
    volumes:
      - ./:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: 127.0.0.1:24224
        tag: apache.access

  fluentd:
    build: docker/fluentd
    volumes:
      - ./docker/fluentd/:/fluentd/etc
    ports:
      - 24224:24224
      - 24224:24224/udp

  elasticsearch:
    image: elasticsearch
    expose:
      - 9200
    ports:
      - 9200:9200

  kibana:
    image: kibana
    ports:
      - 5601:5601